### ISSUE TITLE
Add section for supported networks to the website 

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/safe-landing-page#1]
## Overview

Currently we only mention the supported networks in a small and hardly visible section. 

<img width="403" alt="Screenshot 2021-12-03 at 13 49 23" src="https://user-images.githubusercontent.com/93598450/144605328-8e2ae50d-a6e1-41a2-b2c9-d551f0d33f27.png">

## Goals

Prominently highlight the supported networks on the website

## Requirements

- [ ] design specification 
- [ ] logos 
- [ ] Load supported networks from gateway

## Screens

rough draft tbd with @liliiaorlenko 

![Networks safe drawio](https://user-images.githubusercontent.com/93598450/144604986-28a17f15-de30-44d9-b2db-2ee0a9ba29b7.png)

 - Figma: https://www.figma.com/file/F6xayQPByTA0y6pFzfzuTE/Main-Page?node-id=1%3A77
 - Zeplin:

**Comment by liliiaorlenko** [comment]
Designs with logos:
https://www.figma.com/file/F6xayQPByTA0y6pFzfzuTE/Main-Page?node-id=1%3A77
