### ISSUE TITLE
Update supported networks

### ISSUE THREAD

**Issue by mikhailxyz** [safe-global/safe-landing-page#46]
## Overview

Atm the list is missing avalanche, optimism, aurora

## Goals
keep users updated with our swift rollouts

## Requirements
Avalanche, optimism, and aurora is added to the network list on the landing page

## Screens
![telegram-cloud-photo-size-2-5431723849831005325-y](https://user-images.githubusercontent.com/16622558/166125081-279ef580-4604-4ac8-8fcb-f4e44689aebc.jpg)

**Comment by katspaugh** [comment]
Good call but a duplicate of #1.

**Comment by mikhailxyz** [comment]
@katspaugh, to me, #1 feels more about redesign rather than keeping the information up to date, not to mention it has been open for half a year already
